Updating GC logging options for detailed logging
microsoft/aqa-tests pull request #13
Opened 2023-04-12 22:38 UTC by nitinsingh130519

2023-04-12 22:52 UTC, nitinsingh130519 commented
@kthatipally

2023-04-12 23:04 UTC, dhanalla requested changes

2023-04-12 23:04 UTC, dhanalla commented on perf/renaissance-jmh/gen_playlist.py
> +    file.write("\t\t\t$(JAVA_COMMAND) $(ADD_OPENS_CMD) $(JVM_OPTIONS) -Xlog:gc*,gc+ref=debug,gc+phases=debug,gc+age=trace,gc+ergo*=trace,safepoint:file=gc.log" + bench + "_gc.log -XX:+UseG1GC -Xms12G
remove gc.log as bench+"_gc.log" is already takes care of passing gc file specific to bench.
gc+ref=debug,gc+phases=debug,gc+age=trace,gc+ergo*=trace,safepoint:file=**gc.log**

2023-04-13 15:52 UTC, dhanalla approved these changes

2023-04-14 05:52 UTC, merged

2023-04-14 05:53 UTC, karianna commented
reminder to upstream this to Adoptium if appropriate

2023-04-14 16:25 UTC, gdams commented
@nitinsingh130519 do you not need to run the python updater script to actually update the playlist.xml file?